
server:
  port: 8080
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/api/product-service/** 
          filters:
            - StripPrefix=1
        - id: cart
          uri: http://localhost:8083
          predicates:
            - Path=/api/cart-service/**
          filters:
            - StripPrefix=1
        - id: order
          uri: http://localhost:8084
          predicates:
            - Path=/api/order-service/**
          filters:
            - StripPrefix=1
